/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticket;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Random;

/**
 *
 * @author HP
 */
public class TrainsTickers extends javax.swing.JFrame {

    /**
     * Creates new form TrainsTickers
     */
    public TrainsTickers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1100, 700));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 96)); // NOI18N
        jLabel1.setText("Train Ticketing System");
        jLabel1.setPreferredSize(new java.awt.Dimension(707, 111));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(1400, 700));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel4.setPreferredSize(new java.awt.Dimension(1400, 700));

        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton1.setText("Standard");
        jRadioButton1.setName(""); // NOI18N

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton2.setText("Economy");

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton3.setText("First Class");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Class");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Ticket Type");

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton4.setText("Single");

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton5.setText("Return");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Adult");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Child");

        jRadioButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton6.setText("Yes");

        jRadioButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jRadioButton7.setText("Yes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Destination");

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rangpur", "Chittagong", "Sylhet", "Cox's Bazar" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel2))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1))))
                        .addGap(12, 12, 12))
                    .addComponent(jRadioButton3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton5))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jLabel4))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jRadioButton7)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton5)
                                    .addComponent(jRadioButton3)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButton2))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton6))
                                .addGap(4, 4, 4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(1400, 700));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel5.setPreferredSize(new java.awt.Dimension(1400, 700));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel6.setPreferredSize(new java.awt.Dimension(1400, 700));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Sub Total");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Tax");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("Total");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setText("Total");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addGap(1338, 1338, 1338)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel7.setPreferredSize(new java.awt.Dimension(1400, 700));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 8));
        jPanel8.setPreferredSize(new java.awt.Dimension(1400, 700));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 904, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 920, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Class");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Ticket Type");

        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("From");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setText("To");

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel21.setText("Date");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel22.setText("Time");

        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel24.setText("Ticket No.");

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("Price");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel29.setText("Ticket Type");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15)
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel26)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(1861, 1861, 1861))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel20)
                                        .addComponent(jLabel14)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel22))
                                    .addGap(91, 91, 91)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jPanel7Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addGap(31, 31, 31)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addGap(1338, 1338, 1338)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(23, 23, 23)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(37, 37, 37)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 622, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(5629, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(522, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       this.getContentPane().setBackground(Color.black); // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
      System.exit(0);  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       jLabel10.setText(null); // TODO add your handling code here:
       jLabel11.setText(null); // TODO add your handling code here:
       jLabel12.setText(null); // TODO add your handling code here:
       jLabel23.setText(null); // TODO add your handling code here:
       jLabel27.setText(null); // TODO add your handling code here:
       jLabel30.setText(null); // TODO add your handling code here:
       jLabel25.setText(null); // TODO add your handling code here:
       jLabel17.setText(null); // TODO add your handling code here:
       jLabel18.setText(null); // TODO add your handling code here:
       jLabel19.setText(null); // TODO add your handling code here:
       jLabel16.setText(null); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //***********Setting up Time************
        
        Calendar timer=Calendar.getInstance();
       timer.getTime();
    SimpleDateFormat tTime= new SimpleDateFormat("HH:mm:ss");
    jLabel25.setText(tTime.format(timer.getTime()));//Time
         // TODO add your handling code here:
         //************Setting up Date*************
          SimpleDateFormat tDate = new  SimpleDateFormat("dd:MM:yyyy");
         jLabel18.setText(tDate.format(timer.getTime()));//Date
         
         jLabel19.setText("Dhaka");//From
         jLabel17.setText((String) jComboBox1.getSelectedItem()+" *");//To
         
         //***********Setting up random number Generator***********
         int num1;
         String q1="";
         num1=1325 +(int) (Math.random()*4238);
         q1+=num1+1325;
         jLabel23.setText(q1);//Ticket no
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     double tax =19.50;   // TODO add your handling code here:
     double Milesk8 =25.78;   // TODO add your handling code here:
     double Milesk12 =25.10;   // TODO add your handling code here:
     double Milesk20 =45.23;   // TODO add your handling code here:
     double Milesk30 =55.98;   // TODO add your handling code here:
     double totalcost,eco=3.85,fclass=5.60; 
                       
        //************stndrd+single+adult+Rangpur*****************
     
        if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*Milesk8)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk8+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
                 //************stndrd+return+adult+Rangpur*****************
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*(Milesk8*2))/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk8+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
                    //************stndrd+single+child+Rangpur*****************
                     
        else if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*Milesk8)/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk8+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
                       //************stndrd+return+child+Rangpur*****************
        
          else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*(Milesk8*2))/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk8+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
        
        
              //************stndrd+single+adult+Chittagong*****************
     
       else if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*Milesk12)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk12+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
          //************stndrd+return+adult+Chittagong*****************
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*(Milesk12*2))/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk12+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
        
          //************stndrd+single+child+Chittagong*****************
                     
        else if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*Milesk12)/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk12+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
             //************stndrd+return+child+Chittagong*****************
        
          else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*(Milesk12*2))/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk12+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
        
        
          //************stndrd+single+adult+Sylhet*****************
     
       else if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*Milesk20)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk20+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
                 //************stndrd+return+adult+Sylhet*****************
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*(Milesk20*2))/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk20+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
                    //************stndrd+single+child+Sylhet*****************
                     
        else if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*Milesk20)/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk20+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
                       //************stndrd+return+child+Sylhet****************
        
          else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*(Milesk8*2))/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk8+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
            
        
           //************stndrd+single+adult+Cox's Bazar*****************
     
       else if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*Milesk30)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk30+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
                 //************stndrd+return+adult+Cox's Bazar*****************
        else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*(Milesk30*2))/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk30+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
                    //************stndrd+single+child+Cox's Bazar*****************
                     
        else if((jRadioButton1.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*Milesk30)/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk30+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Standard");
                     
                }
        
                       //************stndrd+return+child+Cox's Bazar****************
        
          else if((jRadioButton1.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*(Milesk30*2))/100;
                    String sTax=String.format("$%.2f", totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk30+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Standard");
                     
                }
        
        //*********************ECONOMY*********************************
          //************Economy+single+adult+Rangpur*****************
     
          else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*Milesk8)/100;
                    String sTax=String.format("$%.2f", eco+totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk8+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
                 //************economy+return+adult+Rangpur*****************
        else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*(Milesk8*2))/100;
                    String sTax=String.format("$%.2f", eco+totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk8+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
                    //************Economy+single+child+Rangpur*****************
                     
        else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*Milesk8)/100;
                    String sTax=String.format("$%.2f", eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk8+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
                       //************Economy+return+child+Rangpur*****************
        
          else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*(Milesk8*2))/100;
                    String sTax=String.format("$%.2f", eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk8+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
        
             //************Economy+single+adult+Chittagong*****************
     
       else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*Milesk12)/100;
                    String sTax=String.format("$%.2f", eco+totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk12+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
          //************Economy+return+adult+Chittagong*****************
        else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*(Milesk12*2))/100;
                    String sTax=String.format("$%.2f", eco+totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk12+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
        
          //************Economy+single+child+Chittagong*****************
                     
        else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*Milesk12)/100;
                    String sTax=String.format("$%.2f",eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk12+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
             //************Economy+return+child+Chittagong*****************
        
          else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*(Milesk12*2))/100;
                    String sTax=String.format("$%.2f",eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk12+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
        
        
           //************Economy+single+adult+Sylhet*****************
     
       else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*Milesk20)/100;
                    String sTax=String.format("$%.2f", eco+totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk20+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
                 //************Economy+return+adult+Sylhet*****************
        else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*(Milesk20*2))/100;
                    String sTax=String.format("$%.2f",eco+totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk20+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
                    //************Economy+single+child+Sylhet*****************
                     
        else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*Milesk20)/100;
                    String sTax=String.format("$%.2f", eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk20+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
                       //************Economy+return+child+Sylhet****************
        
          else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*(Milesk20*2))/100;
                    String sTax=String.format("$%.2f", eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk20+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
        
                  //************Economy+single+adult+Cox's Bazar*****************
     
       else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*Milesk30)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk30+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
                 //************Economy+return+adult+Cox's Bazar*****************
        else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*(Milesk30*2))/100;
                    String sTax=String.format("$%.2f",eco+totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", (Milesk30+totalcost) * 2);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
                    //************Economy+single+child+Cox's Bazar*****************
                     
        else if((jRadioButton2.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*Milesk30)/100;
                    String sTax=String.format("$%.2f", eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk30+totalcost-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("Economy");
                     
                }
        
                       //************Economy+return+child+Cox's Bazar****************
        
          else if((jRadioButton2.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*(Milesk30*2))/100;
                    String sTax=String.format("$%.2f", eco+totalcost-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk30+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("Economy");
                     
                }
        //**************************FIRST CLASS******************************
         //************FIRST CLASS+single+adult+Rangpur*****************
     
          else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=((tax*Milesk8)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk8+fclass+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                 //************FIRST CLASS+return+adult+Rangpur*****************
        else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*(Milesk8*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk8+totalcost)*2)+fclass);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
                    //************FIRST CLASS+single+child+Rangpur*****************
                     
        else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=((tax*Milesk8)+fclass)/100;
                    String sTax=String.format("$%.2f", (totalcost+fclass)-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk8+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk8+totalcost+fclass-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                       //************FIRST CLASS+return+child+Rangpur*****************
        
          else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Rangpur"))
                {
                    totalcost=(tax*(Milesk8*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", (Milesk8 * 2)+fclass);
                    jLabel10.setText(subTotal);
               String Total=String.format("$%.2f", fclass+((Milesk8+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
          //************FIRST CLASS+single+adult+Chittagong*****************
     
          else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=((tax*Milesk12)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk12+fclass+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                 //************FIRST CLASS+return+adult+Chittagong*****************
        else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*(Milesk12*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk12+totalcost)*2)+fclass);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
                    //************FIRST CLASS+single+child+Chittagong*****************
                     
        else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=((tax*Milesk12)+fclass)/100;
                    String sTax=String.format("$%.2f", (totalcost+fclass)-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk12+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk12+totalcost+fclass-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                       //************FIRST CLASS+return+child+Chittagong*****************
        
          else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Chittagong"))
                {
                    totalcost=(tax*(Milesk12*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", (Milesk12 * 2)+fclass);
                    jLabel10.setText(subTotal);
               String Total=String.format("$%.2f", fclass+((Milesk12+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        //************FIRST CLASS+single+adult+Sylhet*****************
     
          else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=((tax*Milesk20)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk20+fclass+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                 //************FIRST CLASS+return+adult+Sylhet*****************
        else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*(Milesk20*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk20+totalcost)*2)+fclass);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
                    //************FIRST CLASS+single+child+Sylhet*****************
                     
        else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=((tax*Milesk20)+fclass)/100;
                    String sTax=String.format("$%.2f", (totalcost+fclass)-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk20+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk20+totalcost+fclass-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                       //************FIRST CLASS+return+child+Sylhet*****************
        
          else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Sylhet"))
                {
                    totalcost=(tax*(Milesk20*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", (Milesk20 * 2)+fclass);
                    jLabel10.setText(subTotal);
               String Total=String.format("$%.2f", fclass+((Milesk20+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
         //************FIRST CLASS+single+adult+Cox's Bazar*****************
     
          else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=((tax*Milesk30)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk30+fclass+totalcost);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                 //************FIRST CLASS+return+adult+Cox's Bazar*****************
        else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton6.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*(Milesk30*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30 * 2);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", ((Milesk30+totalcost)*2)+fclass);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
                    //************FIRST CLASS+single+child+Cox's Bazar*****************
                     
        else if((jRadioButton3.isSelected())&&(jRadioButton4.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=((tax*Milesk30)+fclass)/100;
                    String sTax=String.format("$%.2f", (totalcost+fclass)-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", Milesk30+fclass);
                    jLabel10.setText(subTotal);
                     String Total=String.format("$%.2f", Milesk30+totalcost+fclass-18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("ONE WAY");
                     jLabel16.setText("FIRST CLASS");
                     
                }
        
                       //************FIRST CLASS+return+child+Cox's Bazar*****************
        
          else if((jRadioButton3.isSelected())&&(jRadioButton5.isSelected())&&
     (jRadioButton7.isSelected()) && jComboBox1.getSelectedItem().equals("Cox's Bazar"))
                {
                    totalcost=(tax*(Milesk30*2)+fclass)/100;
                    String sTax=String.format("$%.2f", totalcost+fclass-18);
                    jLabel11.setText(sTax);
                    String subTotal=String.format("$%.2f", (Milesk30 * 2)+fclass);
                    jLabel10.setText(subTotal);
               String Total=String.format("$%.2f", fclass+((Milesk30+totalcost) * 2) - 18);
                     jLabel12.setText(Total);
                     jLabel27.setText(Total);
                     jLabel30.setText("RETURN");
                     jLabel16.setText("FIRST CLASS");
                     
                }
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainsTickers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainsTickers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    // End of variables declaration//GEN-END:variables
}
